name: text_shader
type: graphics
stages:
  - type: vertex
    path: text_shader.vert.glsl
  - type: fragment
    path: text_shader.frag.glsl
options:
  depth_test_enable: true
  depth_write_enable: true
  depth_compare_op: less
  primitive_topology: triangle_list
  cull_mode: back
  polygon_mode: fill
  front_face: counter_clockwise
bindings:
  - binding: 0
    input_rate: vertex
    stride: 20
  - binding: 1
    input_rate: instance
    stride: 24
attributes:
  - type: float3 # model position
    location: 0
    binding: 0
    offset: 0
  - type: float2 # model uv
    location: 1
    binding: 0
    offset: 12
  - type: float3 # instance position
    location: 2
    binding: 1
    offset: 0
  - type: float3 # instance color
    location: 3
    binding: 1
    offset: 12
